<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration {
    public function up(): void
    {
        $orgs = [
            [
                'name' => 'Universidad Panamericana (UP)',
                'short_name' => 'UP',
                'type' => 'university',
                'allowed_email_domains' => json_encode(['@up.edu.mx']),
                'address' => 'Augusto Rodin 498, Insurgentes Mixcoac, Benito Juárez, CDMX',
                'latitude' => 19.3804,
                'longitude' => -99.1802,
                'logo' => 'organizations/up.png',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Escuela Bancaria y Comercial (EBC)',
                'short_name' => 'EBC',
                'type' => 'university',
                'allowed_email_domains' => json_encode(['@ebc.edu.mx', '@alumno.ebc.edu.mx']),
                'address' => 'Campus Reforma, Dinamarca, Toluca y Tlalnepantla',
                'latitude' => 19.2891,
                'longitude' => -99.6412,
                'logo' => 'organizations/ebc.png',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Universidad Insurgentes (UIN)',
                'short_name' => 'UIN',
                'type' => 'university',
                'allowed_email_domains' => json_encode(['@uin.edu.mx']),
                'address' => 'Planteles CDMX y Estado de México (Toluca, Tlalnepantla, etc.)',
                'latitude' => 19.2905,
                'longitude' => -99.6543,
                'logo' => 'organizations/uin.png',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Universidad Pedagógica Nacional (UPN)',
                'short_name' => 'UPN',
                'type' => 'university',
                'allowed_email_domains' => json_encode(['@upn.mx']),
                'address' => 'Carretera al Ajusco 24, Héroes de Padierna, Tlalpan, CDMX',
                'latitude' => 19.2995,
                'longitude' => -99.2185,
                'logo' => 'organizations/upn.png',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'El Colegio de México (COLMEX)',
                'short_name' => 'COLMEX',
                'type' => 'university',
                'allowed_email_domains' => json_encode(['@colmex.mx']),
                'address' => 'Carretera Picacho Ajusco 20, Fuentes del Pedregal, Tlalpan, CDMX',
                'latitude' => 19.3032,
                'longitude' => -99.2186,
                'logo' => 'organizations/colmex.png',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Centro de Investigación y Docencia Económicas (CIDE)',
                'short_name' => 'CIDE',
                'type' => 'university',
                'allowed_email_domains' => json_encode(['@cide.edu']),
                'address' => 'Carretera México-Toluca 3655, Santa Fe, Álvaro Obregón, CDMX',
                'latitude' => 19.3739,
                'longitude' => -99.2612,
                'logo' => 'organizations/cide.png',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Universidad del Claustro de Sor Juana',
                'short_name' => 'Claustro',
                'type' => 'university',
                'allowed_email_domains' => json_encode(['@elclaustro.edu.mx']),
                'address' => 'José María Izazaga 92, Centro Histórico, Cuauhtémoc, CDMX',
                'latitude' => 19.4262,
                'longitude' => -99.1368,
                'logo' => 'organizations/claustro.png',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Universidad ICEL',
                'short_name' => 'ICEL',
                'type' => 'university',
                'allowed_email_domains' => json_encode(['@icel.edu.mx']),
                'address' => 'Planteles CDMX y Estado de México',
                'latitude' => 19.4005,
                'longitude' => -99.1550,
                'logo' => 'organizations/icel.png',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Universidad de las Américas CDMX (UDLA)',
                'short_name' => 'UDLA CDMX',
                'type' => 'university',
                'allowed_email_domains' => json_encode(['@udla.mx']),
                'address' => 'Puebla 223, Roma Norte, Cuauhtémoc, CDMX',
                'latitude' => 19.4201,
                'longitude' => -99.1662,
                'logo' => 'organizations/udla.png',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tecnológico de Monterrey (Campus Toluca)',
                'short_name' => 'ITESM Toluca',
                'type' => 'university',
                'allowed_email_domains' => json_encode(['@tec.mx', '@itesm.mx']),
                'address' => 'Eduardo Monroy Cárdenas 2000, San Antonio Buenavista, Toluca, Edo Méx',
                'latitude' => 19.2635,
                'longitude' => -99.7042,
                'logo' => 'organizations/tec.png',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tecnológico de Monterrey (Campus Estado de México)',
                'short_name' => 'ITESM CEM',
                'type' => 'university',
                'allowed_email_domains' => json_encode(['@tec.mx', '@itesm.mx']),
                'address' => 'Carretera Lago de Guadalupe Km 3.5, Atizapán de Zaragoza, Edo Méx',
                'latitude' => 19.5938,
                'longitude' => -99.2274,
                'logo' => 'organizations/tec.png',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tecnológico de Monterrey (Campus Ciudad de México)',
                'short_name' => 'ITESM CCM',
                'type' => 'university',
                'allowed_email_domains' => json_encode(['@tec.mx', '@itesm.mx']),
                'address' => 'Calle del Puente 222, Ejidos de Huipulco, Tlalpan, CDMX',
                'latitude' => 19.2842,
                'longitude' => -99.1382,
                'logo' => 'organizations/tec.png',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Instituto Tecnológico de Toluca (ITT)',
                'short_name' => 'IT Toluca',
                'type' => 'university',
                'allowed_email_domains' => json_encode(['@toluca.tecnm.mx']),
                'address' => 'Av. Tecnológico s/n, Agrícola Bellavista, Metepec, Edo Méx',
                'latitude' => 19.2555,
                'longitude' => -99.5815,
                'logo' => 'organizations/ittoluca.png',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Universidad Autónoma de Chapingo (UACh)',
                'short_name' => 'Chapingo',
                'type' => 'university',
                'allowed_email_domains' => json_encode(['@chapingo.mx']),
                'address' => 'Km 38.5 Carretera México-Texcoco, Texcoco, Edo Méx',
                'latitude' => 19.4932,
                'longitude' => -98.8821,
                'logo' => 'organizations/chapingo.png',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Universidad Politécnica del Valle de Toluca (UPVT)',
                'short_name' => 'UPVT',
                'type' => 'university',
                'allowed_email_domains' => json_encode(['@upvt.edu.mx']),
                'address' => 'Carretera Toluca-Almoloya de Juárez Km 5.6, Almoloya de Juárez, Edo Méx',
                'latitude' => 19.3361,
                'longitude' => -99.7392,
                'logo' => 'organizations/upvt.png',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Universidad Politécnica del Valle de México (UPVM)',
                'short_name' => 'UPVM',
                'type' => 'university',
                'allowed_email_domains' => json_encode(['@upvm.edu.mx']),
                'address' => 'Av. del Parque 100, Tultitlán, Edo Méx',
                'latitude' => 19.6134,
                'longitude' => -99.1625,
                'logo' => 'organizations/upvm.png',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tecnológico de Estudios Superiores de Ecatepec (TESE)',
                'short_name' => 'TESE',
                'type' => 'university',
                'allowed_email_domains' => json_encode(['@tese.edu.mx']),
                'address' => 'Av. Tecnológico s/n, Valle de Anáhuac, Ecatepec, Edo Méx',
                'latitude' => 19.5255,
                'longitude' => -99.0345,
                'logo' => 'organizations/tese.png',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tecnológico de Estudios Superiores de Coacalco (TESCo)',
                'short_name' => 'TESCo',
                'type' => 'university',
                'allowed_email_domains' => json_encode(['@tesco.edu.mx']),
                'address' => 'Av. 16 de Septiembre 54, Coacalco de Berriozábal, Edo Méx',
                'latitude' => 19.6382,
                'longitude' => -99.0984,
                'logo' => 'organizations/tesco.png',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Universidad Tecnológica Fidel Velázquez (UTFV)',
                'short_name' => 'UTFV',
                'type' => 'university',
                'allowed_email_domains' => json_encode(['@utfv.edu.mx']),
                'address' => 'Emiliano Zapata s/n, Nicolás Romero, Edo Méx',
                'latitude' => 19.6151,
                'longitude' => -99.3021,
                'logo' => 'organizations/utfv.png',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($orgs as $org) {
            $exists = DB::table('taxi_community_organizations')
                ->where('name', $org['name'])
                ->orWhere('short_name', $org['short_name'])
                ->exists();

            if (!$exists) {
                DB::table('taxi_community_organizations')->insert($org);
            }
        }
    }

    public function down(): void
    {
    }
};
