import re

file_path = '/Users/giovannavilchis/Herd/back3.6/resources/views/vendor-views/auth/general-info.blade.php'

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

replacements = {
    r"translate\('messages\.vendor_registration'\)": "'Registro de Restaurante/Tienda'",
    r"translate\('messages\.vendor'\)": "'Restaurante/Tienda'",
    r"translate\('application'\)": "'Registro'",
    r"translate\('General Info'\)": "'Información General'",
    r"translate\('Business Plan'\)": "'Plan de Negocios'",
    r"translate\('Complete'\)": "'Completado'",
    r"translate\('messages\.vendor_info'\)": "'Información del Negocio'",
    r"translate\('Default'\)": "'Por defecto'",
    r"translate\('messages\.name'\)": "'Nombre'",
    r"translate\('messages\.Default'\)": "'Por defecto'",
    r"translate\('messages\.vendor_name'\)": "'Nombre del negocio'",
    r"translate\('messages\.address'\)": "'Dirección'",
    r"translate\('messages\.default'\)": "'Por defecto'",
    r"translate\('Ex: ABC Company'\)": "'Ej: Mi Restaurante'",
    r"translate\('messages\.business_zone'\)": "'Zona del negocio'",
    r"translate\('messages\.select_zone'\)": "'Selecciona una zona'",
    r"translate\('messages\.business_module'\)": "'Módulo del negocio'",
    r"translate\('messages\.select_module'\)": "'Selecciona un módulo'",
    r"translate\('messages\.Select_zone_first'\)": "'Selecciona una zona primero'",
    r"translate\('messages\.approx_delivery_time'\)": "'Tiempo aprox. de entrega'",
    r"translate\('messages\.min'\)": "'Mín'",
    r"translate\('messages\.max'\)": "'Máx'",
    r"translate\('messages\.minutes'\)": "'Minutos'",
    r"translate\('messages\.hours'\)": "'Horas'",
    r"translate\('messages\.days'\)": "'Días'",
    r"translate\('messages\.search_your_location_here'\)": "'Busca tu ubicación aquí'",
    r"translate\('messages\.search_here'\)": "'Buscar aquí'",
    r"translate\('messages\.Please place the marker inside the available zones\.'\)": "'Por favor, coloca el marcador dentro de las zonas disponibles.'",
    r"translate\('messages\.cover'\)": "'Foto de Portada'",
    r"translate\(IMAGE_FORMAT\.' ' \. 'Less Than 2MB'\)": "'Menos de 2MB (JPG/PNG)'",
    r"translate\('\(Ratio 2:1\)'\)": "'(Proporción 2:1)'",
    r"translate\('messages\.Click to upload'\)": "'Haz clic para subir'",
    r"translate\('messages\.or drag and drop'\)": "'o arrastra y suelta aquí'",
    r"translate\('messages\.logo'\)": "'Logo'",
    r"translate\('\(Ratio 1:1\)'\)": "'(Proporción 1:1)'",
    r"translate\('messages\.owner_information'\)": "'Información del Propietario'",
    r"translate\('messages\.Insert_Owner\\'s_General_Information'\)": "'Ingresa la información general del propietario'",
    r"translate\('messages\.first_name'\)": "'Nombre(s)'",
    r"translate\('messages\.last_name'\)": "'Apellido(s)'",
    r"translate\('messages\.phone'\)": "'Teléfono'",
    r"translate\('messages\.Ex:'\)": "'Ej:'",
    r"translate\('Business TIN'\)": "'Información Fiscal'",
    r"translate\('Taxpayer Identification Number\(TIN\)'\)": "'RFC'",
    r"translate\('Type Your Taxpayer Identification Number\(TIN\)'\)": "'Ingresa tu RFC'",
    r"translate\('Expire Date'\)": "'Fecha de expiración (opcional)'",
    r"translate\('TIN Certificate'\)": "'Constancia de Situación Fiscal'",
    r"translate\('pdf, doc, jpg\. File size : max 2 MB'\)": "'pdf, doc, jpg. Tamaño máx: 2 MB'",
    r"translate\('messages\.Select_a_file_or'\)": "'Selecciona un archivo o'",
    r"translate\('messages\.Drag & Drop'\)": "'Arrastra y suelta'",
    r"translate\('messages\.here'\)": "'aquí'",
    r"translate\('messages\.account_information'\)": "'Información de la Cuenta'",
    r"translate\('Insert_Owner\\'s_account_information'\)": "'Ingresa la información de acceso de la cuenta'",
    r"translate\('messages\.email'\)": "'Correo electrónico'",
    r"translate\('messages\.password'\)": "'Contraseña'",
    r"translate\('messages\.password_length_placeholder', \['length' => '8\+'\]\)": "'8+ caracteres'",
    r"translate\('messages\.password_not_matched'\)": "'Las contraseñas no coinciden'",
    r"translate\('messages\.confirm_password'\)": "'Confirmar contraseña'",
    r"translate\('Enter recaptcha value'\)": "'Ingresa el código captcha'",
    r"translate\('Reset'\)": "'Reiniciar'",
    r"translate\('Next'\)": "'Siguiente'",
    r"translate\('messages\.submit'\)": "'Enviar'",
    r"translate\('Choose Your Business Plan'\)": "'Elige tu Plan de Negocios'",
    r"translate\('Commision_Base'\)": "'Basado en Comisión'",
    r"translate\('vendor will pay'\)": "'El negocio pagará'",
    r"translate\('commission to'\)": "'de comisión a'",
    r"translate\('from each order\. You will get access of all the features and options  in vendor panel , app and interaction with user\.'\)": "'por cada pedido. Tendrás acceso a todas las funciones del panel, la app y podrás interactuar con los clientes.'",
    r"translate\('Subscription_Base'\)": "'Basado en Suscripción'",
    r"translate\('Run vendor by puchasing subsciption packages\. You will have access the features of in vendor panel , app and interaction with user according to the subscription packages\.'\)": "'Opera tu negocio comprando paquetes de suscripción. Tendrás acceso a las funciones del panel y app según tu paquete.'",
    r"translate\('Choose Subscription Package'\)": "'Elige un Paquete de Suscripción'",
    r"translate\('Back'\)": "'Atrás'",
    r"translate\('File size must be less than'\)": "'El tamaño del archivo debe ser menor a'",
    r"translate\('Invalid file type\. Allowed: PDF, DOC, JPG, PNG'\)": "'Tipo de archivo inválido. Permitidos: PDF, DOC, JPG, PNG'",
    r"translate\('messages\.Estimated_pickup_time'\)": "'Tiempo estimado de recolección'",
    r"translate\('messages\.pickup_zone'\)": "'Zona de recolección'",
    r"translate\('messages\.Select the zone from where the business will be operated'\)": "'Selecciona la zona desde donde operará el negocio'",
    r"translate\('messages\.Select zones from where customer can choose their pickup locations for trip booking'\)": "'Selecciona las zonas de recolección'",
    r"translate\('Selected Location'\)": "'Ubicación seleccionada'",
    r"translate\('Click_the_map_inside_the_red_marked_area_to_get_Lat/Lng!!!'\)": "'¡Haz clic en el mapa dentro del área marcada para obtener las coordenadas!'",
    r"translate\('Select_Zone_From_The_Dropdown'\)": "'Selecciona una zona del menú'",
    r"translate\('Error:_Your_browser_doesnot_support_geolocation\.'\)": "'Error: Tu navegador no soporta geolocalización.'",
    r"translate\('messages\.out_of_coverage'\)": "'Fuera de cobertura'",
    r"translate\('messages\.Ex:_-94\.22213'\)": "'Ej: -94.22213'",
    r"translate\('messages\.Ex:_103\.344322'\)": "'Ej: 103.344322'",
}

for pattern, rep in replacements.items():
    content = re.sub(pattern, rep, content)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)

print("Translation replacements complete.")
